# Анализ видимости рекламных кампаний

<b>Описание:</b> 

Имеются данные о проведении рекламных кампаний - количество показов рекламного объявления и его средняя позиция в поисковой выдаче. Часть объявлений относятся к брендовым рекламным кампаниям, часть к небрендовым. Известно, что в поисковой выдаче имеется всего 8 позиций (от 1 до 8). 

<b>Цель:</b> 

Определить долю показов рекламных объявлений на позициях топ-1 и топ-3 для брендовых рекламных кампаний, для небрендовых, и общую для всех рекламных кампаний.

## Импорт библиотек и предобработка данных

In [1]:
import pandas as pd
import numpy as np
import re

pd.set_option('max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

Сохраним содержимое файла в переменной `df`.

In [2]:
df = pd.read_excel('dataset_task3.xlsx')
print(f'Длина таблицы: {len(df)}')
df

Длина таблицы: 64

,Дата,Кампания,№ Кампании,Показы,Ср. позиция показов
0,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_srb_yxprrko,69149644,4442,1.10
1,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_url_yxprrko,69149675,2692,1.04
2,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_cch_yxprrko,69149701,1382,1.06
3,янв 2022,o-a_corporate_perform_god_20220100016_context_search_general_szb_yxprrko,69149723,9006,1.24
4,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_msk_yxprrko,69149760,7365,1.24
5,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_bkl_yxprrko,69149785,564,1.05
6,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_vvb_yxprrko,69149811,3184,1.18
7,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_dvb_yxprrko,69149838,443,1.02
8,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_szb_yxprrko,69149868,3245,1.10
9,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_sib_yxprrko,69149899,2089,1.06
10,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_uzb_yxprrko,69149921,2390,1.04
11,янв 2022,o-a_corporate_perform_god_20220100016_context_network_masterkampanii_rus_yxprrko,69718581,10907,2.28
12,янв 2022,o-a_corporate_perform_god_20220100016_context_network_masterkampanii_rus_yxprrko,69772580,887195,2.69
13,янв 2022,o-a_corporate_perform_god_20220100016_context_master_rus_yxprrko,70650826,99818,2.51
14,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_srb_yxprrko,69149644,6670,1.23
15,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_url_yxprrko,69149675,3695,1.18
16,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_cch_yxprrko,69149701,1953,1.17
17,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_szb_yxprrko,69149723,11889,1.15
18,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_msk_yxprrko,69149760,14227,1.60
19,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_bkl_yxprrko,69149785,732,1.20
20,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_vvb_yxprrko,69149811,4450,1.23
21,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_dvb_yxprrko,69149838,724,1.18
22,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_szb_yxprrko,69149868,5299,1.36
23,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_sib_yxprrko,69149899,3179,1.17
24,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_uzb_yxprrko,69149921,3710,1.17
25,фев 2022,o-a_corporate_perform_god_20220100016_context_master_rus_yxprrko,70650826,1209600,3.00
26,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_pvl_yxprrko,71316514,1501,1.26
27,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_srb_yxprrko,71468800,2901,1.65
28,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_url_yxprrko,71468806,1828,1.40
29,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_cch_yxprrko,71468811,947,1.32
30,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_msk_yxprrko,71468817,12345,1.51
31,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_bkl_yxprrko,71468831,375,1.65
32,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_vvb_yxprrko,71468842,2164,1.48
33,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_dvb_yxprrko,71468850,414,1.15
34,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_pvl_yxprrko,71468857,1529,1.30
35,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_sib_yxprrko,71468867,1856,1.33
36,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_uzb_yxprrko,71468876,1802,1.42
37,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_srb_yxprrko,69149644,8929,1.20
38,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_url_yxprrko,69149675,5782,1.11
39,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_cch_yxprrko,69149701,3200,1.15
40,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_szb_yxprrko,69149723,28024,1.26
41,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_msk_yxprrko,69149760,19447,1.79
42,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_bkl_yxprrko,69149785,1307,1.08
43,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_vvb_yxprrko,69149811,6645,1.13
44,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_dvb_yxprrko,69149838,1190,1.11
45,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_szb_yxprrko,69149868,9106,1.27
46,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_sib_yxprrko,69149899,5447,1.20
47,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_uzb_yxprrko,69149921,5476,1.10
48,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_pvl_yxprrko,71316514,5227,1.08
49,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_srb_yxprrko,71468800,28214,1.34
50,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_url_yxprrko,71468806,13842,1.13
51,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_cch_yxprrko,71468811,6875,1.23
52,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_msk_yxprrko,71468817,76691,1.29
53,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_bkl_yxprrko,71468831,2564,1.14
54,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_vvb_yxprrko,71468842,14983,1.16
55,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_dvb_yxprrko,71468850,3199,1.14
56,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_pvl_yxprrko,71468857,10234,1.17
57,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_sib_yxprrko,71468867,13903,1.18
58,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_uzb_yxprrko,71468876,14676,1.11
59,мар 2022,o-a_nbs_corporate_perform_frk_202203000081_context_search_general_rus_yxprrko,72058905,39068,1.18
60,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_wrld_yxprrko,72274259,5886,1.33
61,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_wrld_yxprrko,72274268,23505,1.25
62,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_wrld_yxprrko,72509164,2870,1.34
63,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_wrld_yxprrko,72509174,13670,1.27

In [3]:
df.columns = ['date', 'name_of_campaign', 'num_of_campaign', 'n_shown', 'mean_pos']
df.head()

,date,name_of_campaign,num_of_campaign,n_shown,mean_pos
0,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_srb_yxprrko,69149644,4442,1.10
1,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_url_yxprrko,69149675,2692,1.04
2,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_cch_yxprrko,69149701,1382,1.06
3,янв 2022,o-a_corporate_perform_god_20220100016_context_search_general_szb_yxprrko,69149723,9006,1.24
4,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_msk_yxprrko,69149760,7365,1.24

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              64 non-null     object
 1   name_of_campaign  64 non-null     object
 2   num_of_campaign   64 non-null     int64
 3   n_shown           64 non-null     int64
 4   mean_pos          64 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 2.6+ KB

In [5]:
print(f'Количество дубликатов в таблице: {df.duplicated().sum()}')

Количество дубликатов в таблице: 0

In [6]:
df['date'].value_counts()

мар 2022    27
фев 2022    23
янв 2022    14
Name: date, dtype: int64

Видим, что имеются данные о 64 рекламных объявлениях, размещенных с января по март 2022 года.

In [7]:
print(f'Уникальных номеров рекламных кампаний: {df["num_of_campaign"].nunique()}')
print(f'Уникальных названий рекламных кампаний: {df["name_of_campaign"].nunique()}')

Уникальных номеров рекламных кампаний: 30
Уникальных названий рекламных кампаний: 27

In [8]:
print(f'Дубликатов в датах и номерах кампаний: {df[["date", "num_of_campaign"]].duplicated().sum()}')

Дубликатов в датах и номерах кампаний: 0

In [9]:
df['is_brand'] = df['name_of_campaign'].apply(lambda x: 1 if re.search('brand', x) else 0)
df['is_brand'].value_counts()

1    34
0    30
Name: is_brand, dtype: int64

Из них 34 объявления относятся к брендовым рекдамным кампаниям, 30 - к небрендовым.

In [10]:
df.groupby('num_of_campaign').agg({'is_brand':'nunique'}).query('is_brand > 1')

Empty DataFrame
Columns: [is_brand]
Index: []

In [11]:
df.groupby('name_of_campaign').agg({'is_brand':'nunique'}).query('is_brand > 1')

Empty DataFrame
Columns: [is_brand]
Index: []

Скрытых дубликатов нет.

In [12]:
df.groupby('name_of_campaign').agg({'num_of_campaign':'nunique'}).query('num_of_campaign > 1')

                                                                                  num_of_campaign
name_of_campaign
o-a_corporate_perform_god_20220100016_context_network_masterkampanii_rus_yxprrko                2
o-a_corporate_perform_god_20220100016_context_search_brand_wrld_yxprrko                         2
o-a_corporate_perform_god_20220100016_context_search_general_wrld_yxprrko                       2

In [13]:
display(df.query(
    'name_of_campaign == "o-a_corporate_perform_god_20220100016_context_network_masterkampanii_rus_yxprrko"'))
display(df.query(
    'name_of_campaign == "o-a_corporate_perform_god_20220100016_context_search_brand_wrld_yxprrko"'))
display(df.query(
    'name_of_campaign == "o-a_corporate_perform_god_20220100016_context_search_general_wrld_yxprrko"'))

,date,name_of_campaign,num_of_campaign,n_shown,mean_pos,is_brand
11,янв 2022,o-a_corporate_perform_god_20220100016_context_network_masterkampanii_rus_yxprrko,69718581,10907,2.28,0
12,янв 2022,o-a_corporate_perform_god_20220100016_context_network_masterkampanii_rus_yxprrko,69772580,887195,2.69,0

,date,name_of_campaign,num_of_campaign,n_shown,mean_pos,is_brand
60,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_wrld_yxprrko,72274259,5886,1.33,1
62,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_wrld_yxprrko,72509164,2870,1.34,1

,date,name_of_campaign,num_of_campaign,n_shown,mean_pos,is_brand
61,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_wrld_yxprrko,72274268,23505,1.25,0
63,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_wrld_yxprrko,72509174,13670,1.27,0

Имеются 3 названия рекламных кампаний, у которых есть по 2 разных номера. Поскольку принадлежность к бренду или не бренду для них одинаковая, это не помешает в расчетах, но при возможности необходимо выяснить, почему так получилось. Будем считать, что это особенности названий, и оставим данные позиции в таблице.

Добавим столбец `sum_position`, для которого перемножим количество показов и среднюю позицию показа для каждого рекламного объявления.

In [14]:
df['sum_positions'] = df['n_shown'] * df['mean_pos']
df = df[['date', 'name_of_campaign', 'num_of_campaign', 'is_brand', 
         'n_shown', 'mean_pos', 'sum_positions']]
df

,date,name_of_campaign,num_of_campaign,is_brand,n_shown,mean_pos,sum_positions
0,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_srb_yxprrko,69149644,1,4442,1.10,4886.20
1,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_url_yxprrko,69149675,1,2692,1.04,2799.68
2,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_cch_yxprrko,69149701,1,1382,1.06,1464.92
3,янв 2022,o-a_corporate_perform_god_20220100016_context_search_general_szb_yxprrko,69149723,0,9006,1.24,11167.44
4,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_msk_yxprrko,69149760,1,7365,1.24,9132.60
5,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_bkl_yxprrko,69149785,1,564,1.05,592.20
6,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_vvb_yxprrko,69149811,1,3184,1.18,3757.12
7,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_dvb_yxprrko,69149838,1,443,1.02,451.86
8,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_szb_yxprrko,69149868,1,3245,1.10,3569.50
9,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_sib_yxprrko,69149899,1,2089,1.06,2214.34
10,янв 2022,o-a_corporate_perform_god_20220100016_context_search_brand_uzb_yxprrko,69149921,1,2390,1.04,2485.60
11,янв 2022,o-a_corporate_perform_god_20220100016_context_network_masterkampanii_rus_yxprrko,69718581,0,10907,2.28,24867.96
12,янв 2022,o-a_corporate_perform_god_20220100016_context_network_masterkampanii_rus_yxprrko,69772580,0,887195,2.69,2386554.55
13,янв 2022,o-a_corporate_perform_god_20220100016_context_master_rus_yxprrko,70650826,0,99818,2.51,250543.18
14,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_srb_yxprrko,69149644,1,6670,1.23,8204.10
15,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_url_yxprrko,69149675,1,3695,1.18,4360.10
16,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_cch_yxprrko,69149701,1,1953,1.17,2285.01
17,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_szb_yxprrko,69149723,0,11889,1.15,13672.35
18,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_msk_yxprrko,69149760,1,14227,1.60,22763.20
19,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_bkl_yxprrko,69149785,1,732,1.20,878.40
20,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_vvb_yxprrko,69149811,1,4450,1.23,5473.50
21,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_dvb_yxprrko,69149838,1,724,1.18,854.32
22,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_szb_yxprrko,69149868,1,5299,1.36,7206.64
23,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_sib_yxprrko,69149899,1,3179,1.17,3719.43
24,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_uzb_yxprrko,69149921,1,3710,1.17,4340.70
25,фев 2022,o-a_corporate_perform_god_20220100016_context_master_rus_yxprrko,70650826,0,1209600,3.00,3628800.00
26,фев 2022,o-a_corporate_perform_god_20220100016_context_search_brand_pvl_yxprrko,71316514,1,1501,1.26,1891.26
27,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_srb_yxprrko,71468800,0,2901,1.65,4786.65
28,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_url_yxprrko,71468806,0,1828,1.40,2559.20
29,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_cch_yxprrko,71468811,0,947,1.32,1250.04
30,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_msk_yxprrko,71468817,0,12345,1.51,18640.95
31,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_bkl_yxprrko,71468831,0,375,1.65,618.75
32,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_vvb_yxprrko,71468842,0,2164,1.48,3202.72
33,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_dvb_yxprrko,71468850,0,414,1.15,476.10
34,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_pvl_yxprrko,71468857,0,1529,1.30,1987.70
35,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_sib_yxprrko,71468867,0,1856,1.33,2468.48
36,фев 2022,o-a_corporate_perform_god_20220100016_context_search_general_uzb_yxprrko,71468876,0,1802,1.42,2558.84
37,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_srb_yxprrko,69149644,1,8929,1.20,10714.80
38,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_url_yxprrko,69149675,1,5782,1.11,6418.02
39,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_cch_yxprrko,69149701,1,3200,1.15,3680.00
40,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_szb_yxprrko,69149723,0,28024,1.26,35310.24
41,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_msk_yxprrko,69149760,1,19447,1.79,34810.13
42,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_bkl_yxprrko,69149785,1,1307,1.08,1411.56
43,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_vvb_yxprrko,69149811,1,6645,1.13,7508.85
44,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_dvb_yxprrko,69149838,1,1190,1.11,1320.90
45,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_szb_yxprrko,69149868,1,9106,1.27,11564.62
46,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_sib_yxprrko,69149899,1,5447,1.20,6536.40
47,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_uzb_yxprrko,69149921,1,5476,1.10,6023.60
48,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_pvl_yxprrko,71316514,1,5227,1.08,5645.16
49,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_srb_yxprrko,71468800,0,28214,1.34,37806.76
50,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_url_yxprrko,71468806,0,13842,1.13,15641.46
51,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_cch_yxprrko,71468811,0,6875,1.23,8456.25
52,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_msk_yxprrko,71468817,0,76691,1.29,98931.39
53,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_bkl_yxprrko,71468831,0,2564,1.14,2922.96
54,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_vvb_yxprrko,71468842,0,14983,1.16,17380.28
55,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_dvb_yxprrko,71468850,0,3199,1.14,3646.86
56,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_pvl_yxprrko,71468857,0,10234,1.17,11973.78
57,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_sib_yxprrko,71468867,0,13903,1.18,16405.54
58,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_uzb_yxprrko,71468876,0,14676,1.11,16290.36
59,мар 2022,o-a_nbs_corporate_perform_frk_202203000081_context_search_general_rus_yxprrko,72058905,0,39068,1.18,46100.24
60,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_wrld_yxprrko,72274259,1,5886,1.33,7828.38
61,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_wrld_yxprrko,72274268,0,23505,1.25,29381.25
62,мар 2022,o-a_corporate_perform_god_20220100016_context_search_brand_wrld_yxprrko,72509164,1,2870,1.34,3845.80
63,мар 2022,o-a_corporate_perform_god_20220100016_context_search_general_wrld_yxprrko,72509174,0,13670,1.27,17360.90

Теперь для брендовых, необрендовых и всех рекламных кампаний посчитаем количество показов и среднюю позицию показа.

In [15]:
total_shown_sum = df['n_shown'].sum()
total_positions_sum = df['sum_positions'].sum()
total_mean_pos = total_positions_sum / total_shown_sum
total_part = total_shown_sum / total_shown_sum

brand_shown_sum = df.query('is_brand == 1')['n_shown'].sum()
brand_positions_sum = df.query('is_brand == 1')['sum_positions'].sum()
brand_mean_pos = brand_positions_sum / brand_shown_sum
brand_part = brand_shown_sum / total_shown_sum

no_brand_shown_sum = df.query('is_brand != 1')['n_shown'].sum()
no_brand_positions_sum = df.query('is_brand != 1')['sum_positions'].sum()
no_brand_mean_pos = no_brand_positions_sum / no_brand_shown_sum
no_brand_part = no_brand_shown_sum / total_shown_sum

print('Все компании')
print(f'Всего показов: {total_shown_sum}')
print('Средняя позиция показа: {:.2f}'.format(total_mean_pos), end='\n\n')
print('Брендовые компании')
print(f'Всего показов: {brand_shown_sum}')
print('Доля от всех показов: {:.1%}'.format(brand_part))
print('Средняя позиция показа: {:.2f}'.format(brand_mean_pos), end='\n\n')
print('Не брендовые компании')
print(f'Всего показов: {no_brand_shown_sum}')
print('Доля от всех показов: {:.1%}'.format(no_brand_part))
print('Средняя позиция показа: {:.2f}'.format(no_brand_mean_pos), end='\n\n')

Все компании
Всего показов: 2698472
Средняя позиция показа: 2.56

Брендовые компании
Всего показов: 154448
Доля от всех показов: 5.7%
Средняя позиция показа: 1.30

Не брендовые компании
Всего показов: 2544024
Доля от всех показов: 94.3%
Средняя позиция показа: 2.64

##### Вывод
Данные загружены и предобработаны. 
- Имеются данные от 64 рекламных объявлениях;
- 34 из них брендовые и занимают 5,7% от всех показов, 30  - небрендовые и занимают 94,3% от всех показов;
- Средняя позиция показа для брендовых рекламных объявлений - 1,3, для небрендовых - 2,64, общая для всех рекламных кампаний - 2,56;
- Объявления показывались с января по март 2022 года;
- Дубликатов в данных нет, но есть три пары номеров рекламных кампаний, для каждой пары которых в таблице записано одинакове название.

## Вычисление доли показов рекламной кампании в топ-1 и топ-3 - формула

Средняя позиция показа вычислсяется по формуле 

Средняя позиция показа = $\sum \limits _{i=1} ^{n} x_{i}{i}$ / Всего показов,

где <b><i>i</b></i> - порядковый номер позиции, 

<b><i>n</b></i> - всего возможных позиций, 

<b><i>x</b></i> - количество показов на позиции <b><i>i</b></i>.

В нашем случае известно, что <b><i>n</b></i> = 8.

Поскольку <b>вычислить точное количество показов на каждой позиции не представляется возможным</b> (уравнение с 8-ю неизвестными переменными, недостаточно данных для его решения), <b>оценим минимальное и максимальное</b> возможное количество показов для искомых позиций: в случае топ-1 необходимо вычислить долю показов на позиции 1, в случае топ-3 необходимо вычислить долю показов на позициях 1, 2 и 3 суммарно.

### Топ-1

### Минимальное количество показов на 1-й позиции

Пусть <b><i>x1</b></i> - количество показов на первой позиции. Тогда имеем уравнение:

<b><i>x1</b></i> * 1 = n * avg - $\sum \limits _{i=2} ^{8} x_{i}{i}$,

где <b><i>n</b></i> - всего показов объявления, 

<b><i>avg</b></i> - средняя позиция показа, 

<b><i>i</b></i> - порядковый номер позиции, 

<b><i>x</b></i> - количество показов на позиции <b><i>i</b></i>.

Знаем, что <b><i>x1</b></i> ⩽ n.

Заметим, что $\sum \limits _{i=2} ^{8} x_{i}{i}$ ⩾ 2 * $\sum \limits _{i=2} ^{8} x_{i}$. Тогда

<b><i>x1</b></i> ⩽ n * avg - 2 * $\sum \limits _{i=2} ^{8} x_{i}$

Поскольку $\sum \limits _{i=2} ^{8} x_{i}$ = n - <b><i>x1</b></i>, то

<b><i>x1</b></i> ⩽ n * avg - 2 * (n - <b><i>x1</b></i>)

<b><i>x1</b></i> ⩽ n * avg - 2 * n + 2 * <b><i>x1</b></i>

<b><i>x1</b></i> ⩽ n * (avg - 2) + 2 * <b><i>x1</b></i>

<b><i>x1</b></i> ⩾ n * (2 - avg)

Тогда можем определить минимальное <b><i>x1</b></i>: 

<b><i>x1_min</b></i> = n * (2 - avg)

При этом при <i>avg ⩾ 2</i>: <b><i>x1_min</b></i> = 0

При <i>avg < 2</i> : <b><i>x1_min</b></i> = n * (2 - avg)
    
<i>Действительно, если, например, avg = 2,5, то при n = 1000 показов минимальное количество показов на 1-м месте может быть 0 - в таком случае, например, может быть 500 показов на 2-м месте и 500 показов на 3-м месте.</i>
    
<i>А при avg < 2 логически не может быть такого, чтобы на 1-м месте не было ни одного показа.</i>

### Максимальное количество показов на 1-й позиции

Имеем то же уравнение:

<b><i>x1</b></i> * 1 = n * avg - $\sum \limits _{i=2} ^{8} x_{i}{i}$.

Знаем, что <b><i>x1</b></i> ⩽ n.

Заметим, что $\sum \limits _{i=2} ^{8} x_{i}{i}$ ⩽ 8 * $\sum \limits _{i=2} ^{8} x_{i}$. Тогда

<b><i>x1</b></i> ⩾ n * avg - 8 * $\sum \limits _{i=2} ^{8} x_{i}$

Поскольку $\sum \limits _{i=2} ^{8} x_{i}$ = n - <b><i>x1</b></i>, то

<b><i>x1</b></i> ⩾ n * avg - 8 * (n - <b><i>x1</b></i>)

<b><i>x1</b></i> ⩾ n * avg - 8 * n + 8 * <b><i>x1</b></i>

<b><i>x1</b></i> ⩾ n * (avg - 8) + 8 * <b><i>x1</b></i>

7 * <b><i>x1</b></i> ⩽ n * (8 - avg)

<b><i>x1</b></i> ⩽ n * (8 - avg) / 7

Тогда можем определить максимальное <b><i>x1</b></i>: 

<b><i>x1_max</b></i> = n * (8 - avg) / 7

При этом при <i>avg = 8</i>: <b><i>x1_max</b></i> = 0

При <i>1 < avg < 8</i> : <b><i>x1_max</b></i> = n * (8 - avg) / 7

При <i>avg = 1</i> : <b><i>x1_max</b></i> = n
    
<i>Действительно, при avg = 8 все показы должны были быть на 8-м месте, тогда количество показов на 1-м месте = 0.</i>

<i>При avg = 1 все показы должны были быть на 1-м месте, тогда количество показов на 1-м месте = n.</i>

### Топ-3

### Минимальное количество показов на позициях 1, 2 и 3 суммарно

$\sum \limits _{i=1} ^{3} x_{i}$ - количество показов на 1, 2 и 3-й позициях суммарно. Тогда имеем уравнение:

$\sum \limits _{i=1} ^{3} x_{i}{i}$ = n * avg - $\sum \limits _{i=4} ^{8} x_{i}{i}$,

где <b><i>n</b></i> - всего показов объявления, 

<b><i>avg</b></i> - средняя позиция показа, 

<b><i>i</b></i> - порядковый номер позиции, 

<b><i>x</b></i> - количество показов на позиции <b><i>i</b></i>.

Знаем, что $\sum \limits _{i=1} ^{3} x_{i}$ ⩽ n.

Заметим, что $\sum \limits _{i=4} ^{8} x_{i}{i}$ ⩾ 4 * $\sum \limits _{i=2} ^{8} x_{i}$, а также

$\sum \limits _{i=1} ^{3} x_{i}{i}$ ⩾ $\sum \limits _{i=1} ^{3} x_{i}$. Тогда

$\sum \limits _{i=1} ^{3} x_{i}$ ⩽ $\sum \limits _{i=1} ^{3} x_{i}{i}$ ⩽ n * avg - 4 * $\sum \limits _{i=2} ^{8} x_{i}$

Поскольку $\sum \limits _{i=4} ^{8} x_{i}$ = n - $\sum \limits _{i=1} ^{3} x_{i}$, то

$\sum \limits _{i=1} ^{3} x_{i}$ ⩽ n * avg - 4 * (n - $\sum \limits _{i=1} ^{3} x_{i}$)

$\sum \limits _{i=1} ^{3} x_{i}$ ⩽ n * (avg - 4) + 4 * $\sum \limits _{i=1} ^{3} x_{i}$

3 $\sum \limits _{i=1} ^{3} x_{i}$ ⩾ n * (4 - avg)

$\sum \limits _{i=1} ^{3} x_{i}$ ⩾ n * (4 - avg) / 3

Тогда можем определить минимальное $\sum \limits _{i=1} ^{3} x_{i}$: 

$\sum \limits _{i=1} ^{3} x_{i}$ = n * (4 - avg) / 3

При этом при <i>avg ⩾ 4</i>: $\sum \limits _{i=1} ^{3} x_{i}$ <b><i>min</b></i> = 0

При <i>1 < avg < 4</i> : $\sum \limits _{i=1} ^{3} x_{i}$ <b><i>min</b></i> = n * (4 - avg) / 3

При <i>avg = 1</i> : $\sum \limits _{i=1} ^{3} x_{i}$ <b><i>min</b></i> = n
    
<i>Действительно, если, например, avg = 4,5, то при n = 1000 показов минимальное количество показов на 1, 2 и 3-м месте суммарно может быть 0 - в таком случае, например, может быть 500 показов на 4-м месте и 500 показов на 5-м месте.</i>
    
<i>При avg = 1 все показы будут на 1-м месте, и тогда минимальная доля количества показов в топ-3 будет равна 100%.</i>

### Максимальное количество показов на позициях 1, 2 и 3 суммарно

Имеем то же уравнение:

$\sum \limits _{i=1} ^{3} x_{i}{i}$ = n * avg - $\sum \limits _{i=4} ^{8} x_{i}{i}$.

Знаем, что $\sum \limits _{i=1} ^{3} x_{i}$ ⩽ n.

Заметим, что $\sum \limits _{i=4} ^{8} x_{i}{i}$ ⩽ 8 * $\sum \limits _{i=2} ^{8} x_{i}$, а также

$\sum \limits _{i=1} ^{3} x_{i}{i}$ ⩽ 3 * $\sum \limits _{i=1} ^{3} x_{i}$. Тогда

3 * $\sum \limits _{i=1} ^{3} x_{i}$ ⩾ $\sum \limits _{i=1} ^{3} x_{i}{i}$ ⩾ n * avg - 8 * $\sum \limits _{i=2} ^{8} x_{i}$

Поскольку $\sum \limits _{i=4} ^{8} x_{i}$ = n - $\sum \limits _{i=1} ^{3} x_{i}$, то

3 * $\sum \limits _{i=1} ^{3} x_{i}$ ⩾ n * avg - 8 * (n - $\sum \limits _{i=1} ^{3} x_{i}$)

3 * $\sum \limits _{i=1} ^{3} x_{i}$ ⩾ n * (avg - 8) + 8 * $\sum \limits _{i=1} ^{3} x_{i}$

5 $\sum \limits _{i=1} ^{3} x_{i}$ ⩽ n * (8 - avg)

$\sum \limits _{i=1} ^{3} x_{i}$ ⩽ n * (8 - avg) / 5

Тогда можем определить максимальное $\sum \limits _{i=1} ^{3} x_{i}$: 

$\sum \limits _{i=1} ^{3} x_{i}$ = n * (8 - avg) / 5

При этом при <i>avg ⩽ 3</i>: $\sum \limits _{i=1} ^{3} x_{i}$ <b><i>max</b></i> = n

При <i>3 < avg < 8</i> : $\sum \limits _{i=1} ^{3} x_{i}$ <b><i>max</b></i> = n * (8 - avg) / 5

При <i>avg = 8</i> : $\sum \limits _{i=1} ^{3} x_{i}$ <b><i>max</b></i> = 0
    
<i>Действительно, если, например, avg = 8, то все показы были на 8-й позиции и в топ-3 ничего не попало.</i>
    
<i>При avg = 2,5 и при n = 1000, например, могло быть 500 показов на 2-й позиции и 500 показов на 3-й позиции, то есть все 1000 показов, то есть 100%, приходятся на топ-3 позиции.</i>

<div class="alert alert-success">
    Мы определили формулы для определния минимального и максимального количества показов на топ-1 и топ-3 местах. Для вычисления доли показов необходимо эти цифры разделить на общее количество показов, то есть 
    
    Доля показов объявлений на позиции n = Количество показов объявлений на позиции n / n
</div>

## Вычисление доли показов рекламной кампании в топ-1 и топ-3 - расчеты

Напишем функции для определения минимальной и максимальной доли показов на топ-1 и топ-3 позициях на основании описанных выше формул.

In [16]:
def top_1_min(mean_pos):
    
    if 1 <= mean_pos < 2: 
        return 2 - mean_pos 
    
    elif 2 <= mean_pos <= 8:
        return 0
        
    else:
        return 'incorrect'
    
    
def top_1_max(mean_pos):
    
    if mean_pos == 1:
        return 1 
    
    elif 1 < mean_pos < 8:
        return  (8 - mean_pos) / 7
    
    if mean_pos == 8:
        return 0
    
    else:
        return 'incorrect'
    
    
def top_3_min(mean_pos):
    
    if mean_pos == 1:
        return 1
    
    elif 1 < mean_pos < 4:
        return (4 - mean_pos) / 3
    
    elif 4 <= mean_pos <= 8:
        return 0
    
    else:
        return 'incorrect'
    
    
def top_3_max(mean_pos):
    
    if 1 <= mean_pos <= 3:
        return 1
    
    elif 3 < mean_pos < 8:
        return (8 - mean_pos) / 5
    
    elif mean_pos == 8:
        return 0
    
    else:
        return 'incorrect'

Теперь вычислим минимальные и максимальные значения доли показов на топ-1 и топ-3 местах для брендовых, небрендовых и общий для всех рекламных кампаний.

In [17]:
result = pd.DataFrame(columns=['compaign', 'shown_sum', 'part_of_all',
                               'mean_pos', 'min_part_top_1', 'max_part_top_1',
                               'min_part_top_3', 'max_part_top_3'])

def print_summary(name, shown_sum, mean_pos, part):
    
    global result
    
    print(name)
    print(f'Всего показов: {shown_sum}')
    print('Средняя позиция показа: {:.2f}'.format(mean_pos))
    
    top_1_min_value = top_1_min(mean_pos)
    top_1_max_value = top_1_max(mean_pos)
    top_3_min_value = top_3_min(mean_pos)
    top_3_max_value = top_3_max(mean_pos)
    
    print('Минимальная доля показов на позиции топ-1: {:.1%}'.format(top_1_min_value))
    print('Максимальная доля показов на позиции топ-1: {:.1%}'.format(top_1_max_value))
    print('Минимальная доля показов на позиции топ-3: {:.1%}'.format(top_3_min_value))
    print('Максимальная доля показов на позиции топ-3: {:.1%}'.format(top_3_max_value),
           end='\n\n')
    
    res = pd.DataFrame({'compaign':[name],
                        'shown_sum':[shown_sum],
                        'part_of_all':[part],
                        'mean_pos':[mean_pos],
                        'min_part_top_1':[top_1_min_value],
                        'max_part_top_1':[top_1_max_value],
                        'min_part_top_3':[top_3_min_value],
                        'max_part_top_3':[top_3_max_value]})
    
    result = pd.concat([result, res], ignore_index=True)
    
    return result
    
result = print_summary('Все кампании', total_shown_sum, total_mean_pos, total_part)
result = print_summary('Брендовые кампании', brand_shown_sum, brand_mean_pos, brand_part)
result = print_summary('Небрендовые кампании', no_brand_shown_sum, no_brand_mean_pos, no_brand_part)

Все кампании
Всего показов: 2698472
Средняя позиция показа: 2.56
Минимальная доля показов на позиции топ-1: 0.0%
Максимальная доля показов на позиции топ-1: 77.7%
Минимальная доля показов на позиции топ-3: 47.9%
Максимальная доля показов на позиции топ-3: 100.0%

Брендовые кампании
Всего показов: 154448
Средняя позиция показа: 1.30
Минимальная доля показов на позиции топ-1: 70.1%
Максимальная доля показов на позиции топ-1: 95.7%
Минимальная доля показов на позиции топ-3: 90.0%
Максимальная доля показов на позиции топ-3: 100.0%

Небрендовые кампании
Всего показов: 2544024
Средняя позиция показа: 2.64
Минимальная доля показов на позиции топ-1: 0.0%
Максимальная доля показов на позиции топ-1: 76.6%
Минимальная доля показов на позиции топ-3: 45.4%
Максимальная доля показов на позиции топ-3: 100.0%

In [18]:
col_dict = {'compaign':'Кампании',
            'shown_sum':'Всего показов',
            'part_of_all':'Доля от всех показов',
            'mean_pos':'Средняя позиция показа',
            'min_part_top_1':'Минимальная доля показов на позиции ТОП-1',
            'max_part_top_1':'Максимальная доля показов на позиции ТОП-1',
            'min_part_top_3':'Минимальная доля показов на позиции ТОП-3',
            'max_part_top_3':'Максимальная доля показов на позиции ТОП-3'}

result = result.rename(columns=col_dict)
result = result.set_index('Кампании')
result

,Всего показов,Доля от всех показов,Средняя позиция показа,Минимальная доля показов на позиции ТОП-1,Максимальная доля показов на позиции ТОП-1,Минимальная доля показов на позиции ТОП-3,Максимальная доля показов на позиции ТОП-3
Кампании,,,,,,,
Все кампании,2698472,1.0,2.561599,0,0.776914,0.479467,1
Брендовые кампании,154448,0.057235,1.299071,0.700929,0.957276,0.90031,1
Небрендовые кампании,2544024,0.942765,2.638247,0,0.765965,0.453918,1

In [19]:
result[['Всего показов', 'Доля от всех показов', 'Средняя позиция показа']]\
            .style\
            .set_table_styles([{'selector': 'th', 'props': 'font-size: 13pt'}])\
            .set_properties(**{'font-size': '13pt'})\
            .background_gradient(cmap='binary', subset=['Всего показов', 'Доля от всех показов'])\
            .background_gradient(cmap='BuGn_r', subset=['Средняя позиция показа'])\
            .format('{:,}', subset=['Всего показов'])\
            .format('{:.2f}', subset=['Средняя позиция показа'])\
            .format('{:.1%}', subset=['Доля от всех показов'])

In [20]:
result[['Минимальная доля показов на позиции ТОП-1', 'Максимальная доля показов на позиции ТОП-1',
        'Минимальная доля показов на позиции ТОП-3', 'Максимальная доля показов на позиции ТОП-3']]\
            .style\
            .set_table_styles([{'selector': 'th', 'props': 'font-size: 13pt'}])\
            .set_properties(**{'font-size': '13pt'})\
            .background_gradient(cmap='Blues', subset=['Минимальная доля показов на позиции ТОП-1',
                                                       'Минимальная доля показов на позиции ТОП-3'])\
            .background_gradient(cmap='Oranges', subset=['Максимальная доля показов на позиции ТОП-1',
                                                         'Максимальная доля показов на позиции ТОП-3'])\
            .format('{:.1%}', subset=['Минимальная доля показов на позиции ТОП-1', 
                                      'Максимальная доля показов на позиции ТОП-1',
                                      'Минимальная доля показов на позиции ТОП-3', 
                                      'Максимальная доля показов на позиции ТОП-3'])

##### Вывод
Брендовые кампании с большей вероятностью чаще попадали на топ-1 и топ-3 позиции в поисковой выдаче. Но точно определить нельзя - например, брендовая кампания могла показаться на позиции топ-1 минимальное количество раз - 70,1%, а небрендовая кампания - максимально, то есть 76,6%.

## Вывод
- Имелись данные о 64-х рекламных объявлениях, показанных с января по март 2022 года;
- 34 из них относятся к брендовым кампаниям, 30 - к небрендовым;
- Из всего количества показов (2,7 млн) только 5,7% показов приходятся на брендовые объявления, остальные 94,3% - на небрендовые;
- Средняя позиция показа для брендовых рекламных объявлений - 1,3, для небрендовых - 2,64, общая для всех рекламных кампаний - 2,56;
- Точно определить долю показов объявления на позициях топ-1 и топ-3 по имеющимся данным невозможно, поэтому произведена оценка минимальной и максимальной доли показов;
- Брендовые рекламные кампании с большей вероятностью попадали в топ-1 и топ-3 позиции поисковой выдачи.